#+TITLE: auth-source-pass Configuration
#+AUTHOR: Joseph M LaFreniere (lafrenierejm)
#+EMAIL: joseph@lafreniere.xyz

* License
  All code sections in this file are licensed under [[https://gitlab.com/lafrenierejm/dotfiles/blob/master/LICENSE][an ISC license]] except when otherwise noted.
  All prose in this file is licensed under [[https://creativecommons.org/licenses/by/4.0/][CC BY 4.0]] except when otherwise noted.

* About This File
  This file contains a configuration for Damien Cassou (DameinCassou)'s [[https://github.com/DamienCassou/auth-password-store][auth-source-pass]] package.
  auth-source-pass integrates Jason A. Donenfield (ZX2C4)'s [[https://www.passwordstore.org/][pass]] utility into Emacs's authentication mechanisms.

  This file is written in the [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]] style using [[http://orgmode.org/worg/org-contrib/babel/][Org mode Babel]].

* Code
** Introductory Boilerplate
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no :export no
     ;;; init-auth-source-pass.el --- Configuration for auth-source-pass

     ;;; Commentary:
     ;; This file is tangled from init-auth-source-pass.org.
     ;; Changes made here will be overwritten by changes to that Org file.

     ;;; Code:
   #+END_SRC

** Specify Dependencies
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no :export no
     (require 'use-package)
   #+END_SRC

** Load ~auth-source-pass~
   #+BEGIN_SRC emacs-lisp :tangle yes :noweb yes
     (use-package auth-source-pass
       ;; Only load this package if the following code evaluates to non-nil.
       :if
       <<auth-source-pass/if>>

       ;; Load this package eagerly.
       :demand

       ;; Evaluate the following code after loading this package.
       :config
       <<auth-source-pass/config>>)
   #+END_SRC

*** Conditional Loading (~:if~)
    :PROPERTIES:
    :DESCRIPTION: Only load ~auth-source-pass~ if this condition is met.
    :HEADER-ARGS: :noweb-ref auth-source-pass/if
    :END:

    ~auth-source-pass~ is only usable if =pass= is available in the user's =$PATH=.

    #+BEGIN_SRC emacs-lisp :tangle no
      (executable-find "pass")
    #+END_SRC

*** Post-Load Execution
    :PROPERTIES:
    :HEADER-ARGS: :noweb-ref auth-source-pass/config
    :DESCRIPTION: Code to execute after the parent package has been loaded
    :END:

    Enable auth-source-password-store.

    #+BEGIN_SRC emacs-lisp :tangle no
      (auth-source-pass-enable)
    #+END_SRC

** Ending Boilerplate
   #+BEGIN_SRC emacs-lisp :tangle yes
     (provide 'init-auth-source-pass)
     ;;; init-auth-source-pass.el ends here
   #+END_SRC
