#+TITLE: Line Number Configuration
#+AUTHOR: Joseph M LaFreniere (lafrenierejm)
#+EMAIL: joseph@lafreniere.xyz

* Copyright and Licensing					   :noexport:
  All code sections in this file are licensed under [[https://gitlab.com/lafrenierejm/dotfiles/blob/master/LICENSE][an ISC license]] except when otherwise noted.
  All prose in this file is licensed under [[https://creativecommons.org/licenses/by/4.0/][CC BY 4.0]] except when otherwise noted.

* About This File
  This file contains my configuration for Electric Pair Mode.
  This file is written in the [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]] style using [[http://orgmode.org/worg/org-contrib/babel/][Org mode Babel]].

* Code
** Introductory Boilerplate					   :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no :noweb yes
     ;;; init-linum-mode.el --- Configuration for linum-mode
     ;;
     ;; <<copyright>>
     ;;
     ;;; Commentary:
     ;; This file is tangled from init-linum-mode.org.
     ;; Changes made here will be overwritten by changes to that Org file.

     ;;; Code:
   #+END_SRC

** Specify Dependencies						   :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no
     (require 'use-package)
     (require 'validate)
   #+END_SRC

** Load linum-mode for Version < 26
   #+BEGIN_SRC emacs-lisp :tangle yes :noweb no-export
     (use-package linum-mode
       ;; Only load linum-mode if the following condition is met.
       :if
       <<linum-mode/if>>

       ;; Do not download.
       :ensure nil

       ;; Enable linum-mode via hooks.
       :hook
       <<linum-mode/hook>>)
   #+END_SRC

*** Conditional Loading (~:if~)
    :PROPERTIES:
    :DESCRIPTION: Define condition for loading ~linum-mode~.
    :END:

    Starting in Emacs 26.1, ~linum-mode~ has been deprecated in favor of ~display-line-numbers-mode~.
    As such, ~linum-mode~ should only be loaded when running a version of Emacs older than 26.1

    #+NAME: linum-mode/if
    #+BEGIN_SRC emacs-lisp
      (version< emacs-version "26.1")
    #+END_SRC

*** Enabling via Hooks (~:hook~)
    :PROPERTIES:
    :DESCRIPTION: Add hooks to enable ~linum-mode~.
    :END:

    ~use-package~ provides the ~:hook~ keyword for succinctly adding functions onto hooks.
    One valid syntax for the ~:hook~ specifier is a list of modes to which the package being loaded will be hooked.

    #+NAME: linum-mode/hook
    #+BEGIN_SRC emacs-lisp
      (prog-mode TeX-mode)
    #+END_SRC

** Load ~display-line-numbers~ for Version >= 26.1
   #+BEGIN_SRC emacs-lisp :tangle yes :noweb no-export
     (use-package display-line-numbers
       ;; Only load display-line-numbers if the following condition is met.
       :if
       <<display-line-numbers/if>>

       ;; `display-line-numbers' is included in Emacs.
       :ensure nil

       ;; Load `display-line-numbers' after the following packages.
       :after
       (validate)

       ;; Enable display-line-numbers via hooks.
       :hook
       <<display-line-numbers/hook>>

       :config
       <<display-line-numbers/config>>)
   #+END_SRC

*** Conditional Loading (~:if~)
    :PROPERTIES:
    :DESCRIPTION: Define condition for loading ~display-line-numbers~.
    :END:

    ~display-line-numbers~ is the alternative to ~linum-mode~ and is preferred when available.
    It shall therefore be used in all cases except in those that necessitate using ~linum-mode~.

    #+NAME: display-line-numbers/if
    #+BEGIN_SRC emacs-lisp :noweb no-export
      (not <<linum-mode/if>>)
    #+END_SRC

*** Enabling via Hooks (~:hook~)
    :PROPERTIES:
    :DESCRIPTION: Add hooks to enable ~display-line-numbers~.
    :END:

    ~display-line-numbers-mode~ shall be active in all of the same buffers as ~linum-mode~.

    #+NAME: display-line-numbers/hook
    #+BEGIN_SRC emacs-lisp :noweb no-export
      (<<linum-mode/hook>> . display-line-numbers-mode)
    #+END_SRC

*** Post-Load Execution (~:config~)
    :PROPERTIES:
    :HEADER-ARGS: :noweb-ref display-line-numbers/config
    :END:

    Display relative line numbers for all lines except the current line.

    #+BEGIN_SRC emacs-lisp
      (validate-setq display-line-numbers-type 'relative)
    #+END_SRC

    Display the absolute line number of the current line.

    #+BEGIN_SRC emacs-lisp
      (validate-setq display-line-numbers-current-absolute t)
    #+END_SRC

    Do not shrink line number width.

    #+BEGIN_SRC emacs-lisp
      (validate-setq display-line-numbers-grow-only t)
    #+END_SRC

** Ending Boilerplate                                              :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes
     (provide 'init-linum-mode)
     ;;; init-linum-mode.el ends here
   #+END_SRC
