#+TITLE: diff-hl Configuration
#+AUTHOR: Joseph M LaFreniere (lafrenierejm)
#+EMAIL: joseph@lafreniere.xyz
#+LaTeX_header: \usepackage[margin=1in]{geometry}

* License
  All code sections in this file are licensed under [[https://gitlab.com/lafrenierejm/dotfiles/blob/master/LICENSE][an ISC license]] except when otherwise noted.
  All prose in this file is licensed under [[https://creativecommons.org/licenses/by/4.0/][CC BY 4.0]] except when otherwise noted.

* About This File
  This file contains my configuration for Dmitry Gutov (dgutov)'s [[https://github.com/dgutov/diff-hl][diff-hl]] package.
  diff-hl provides highlighting uncommitted changes to a buffer's file in the buffer's fringe.
  This file is written in the [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]] style using [[http://orgmode.org/worg/org-contrib/babel/][Org mode Babel]].

* Code
** Introductory Boilerplate
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no
     ;;; init-diff-hl.el --- Configuration for diff-hl

     ;;; Commentary:
     ;; This file is tangled from init-diff-hl.org.
     ;; Changes made here will be overwritten by changes to that Org file.

     ;;; Code:
   #+END_SRC

** Specify Dependencies
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no
     (require 'general)
     (require 'use-package)
   #+END_SRC

** Load diff-hl
   #+BEGIN_SRC emacs-lisp :tangle yes :noweb yes
     (use-package diff-hl
       ;; Only load the package if the following condition is met.
       :if
       <<diff-hl/if>>

       ;; Add the following auto-loading hooks.
       :ghook
       <<diff-hl/ghook>>

       ;; Inform the bytecode compiler about the following functions.
       :commands
       global-diff-hl-mode

       ;; Execute the following code after the package has been loaded.
       :config
       <<diff-hl/config>>)
   #+END_SRC

*** Conditional Loading (~:if~)
    :PROPERTIES:
    :HEADER-ARGS: :noweb-ref diff-hl/if
    :END:

    ~diff-hl~ depends on features added in Emacs 24.3.

    #+BEGIN_SRC emacs-lisp :tangle no
      (version<= "24.3" emacs-version)
    #+END_SRC

*** Auto-Loading Hooks (~:ghook~)
    :PROPERTIES:
    :HEADER-ARGS: :noweb-ref diff-hl/ghook
    :END:

    Enable diff-hl in Dired buffers.

    #+BEGIN_SRC emacs-lisp :tangle no
      ('dired-mode-hook #'diff-hl-dired-mode)
    #+END_SRC

    Update ~diff-hl~'s status when refreshing with modern versions of Magit.

    #+BEGIN_SRC emacs-lisp :tangle no
      ('magit-post-refresh-hook #'diff-hl-magit-post-refresh)
    #+END_SRC

*** Post-Load Execution
    :PROPERTIES:
    :HEADER-ARGS: :noweb-ref diff-hl/config
    :END:

    Enable diff-hl-mode by default.

    #+BEGIN_SRC emacs-lisp :tangle no
      (global-diff-hl-mode 1)
    #+END_SRC

    Perform highlighting on-the-fly.

    #+BEGIN_SRC emacs-lisp :tangle no
      (diff-hl-flydiff-mode 1)
    #+END_SRC

** Ending Boilerplate
   #+BEGIN_SRC emacs-lisp :tangle yes :export no
     (provide 'init-diff-hl)
     ;;; init-diff-hl.el ends here
   #+END_SRC
