#+TITLE: Line Number Configuration
#+AUTHOR: Joseph M LaFreniere (lafrenierejm)
#+EMAIL: joseph@lafreniere.xyz

* Copyright and Licensing					   :noexport:
  All code sections in this file are licensed under [[https://gitlab.com/lafrenierejm/dotfiles/blob/master/LICENSE][an ISC license]] except when otherwise noted.
  All prose in this file is licensed under [[https://creativecommons.org/licenses/by/4.0/][CC BY 4.0]] except when otherwise noted.

* About This File
  This file contains my configuration for Electric Pair Mode.
  This file is written in the [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]] style using [[http://orgmode.org/worg/org-contrib/babel/][Org mode Babel]].

* Code
** Introductory Boilerplate					   :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no :noweb yes
     ;;; init-linum-mode.el --- Configuration for linum-mode
     ;;
     ;; <<copyright>>
     ;;
     ;;; Commentary:
     ;; This file is tangled from init-linum-mode.org.
     ;; Changes made here will be overwritten by changes to that Org file.

     ;;; Code:
   #+END_SRC

** Specify Dependencies						   :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no
     (require 'use-package)
   #+END_SRC

** Load linum-mode for Version < 26
   #+BEGIN_SRC emacs-lisp :tangle yes :noweb no-export
     (use-package linum-mode
       ;; Only load linum-mode if the following condition is met.
       :if
       <<linum-mode/if>>

       ;; Do not download with straight.
       :straight nil

       ;; Enable linum-mode via hooks.
       :hook
       <<linum-mode/hook>>)
   #+END_SRC

*** Conditional Loading (~:if~)
    :PROPERTIES:
    :DESCRIPTION: Define condition for loading ~linum-mode~.
    :END:

    Starting in Emacs 26.1, linum-mode has been deprecated in favor of display-line-numbers-mode.
    As such, linum-mode should only be loaded when the version is older than 26.1

    #+NAME: linum-mode/if
    #+BEGIN_SRC emacs-lisp
      (version< emacs-version "26.1")
    #+END_SRC

*** Enabling via Hooks (~:hook~)
    :PROPERTIES:
    :DESCRIPTION: Add hooks to enable ~linum-mode~.
    :END:

    ~use-package~ provides the ~:hook~ keyword for succinctly adding functions onto hooks.
    One valid syntax for the ~:hook~ specifier is a list of modes to which the package being loaded will be hooked.

    #+NAME: linum-mode/hook
    #+BEGIN_SRC emacs-lisp
      (prog-mode TeX-mode)
    #+END_SRC

** Ending Boilerplate 						   :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes
     (provide 'init-linum-mode)
     ;;; init-linum-mode.el ends here
   #+END_SRC
