#+TITLE: Line Number Configuration
#+AUTHOR: Joseph M LaFreniere (lafrenierejm)
#+EMAIL: joseph@lafreniere.xyz
#+PROPERTY: header-args+ :comments link
#+PROPERTY: header-args+ :tangle no

* Copyright and Licensing					   :noexport:
  All code sections in this file are licensed under [[https://gitlab.com/lafrenierejm/dotfiles/blob/master/LICENSE][an ISC license]] except when otherwise noted.
  All prose in this file is licensed under [[https://creativecommons.org/licenses/by/4.0/][CC BY 4.0]] except when otherwise noted.

* About This File
  This file contains my configuration for Electric Pair Mode.
  This file is written in the [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]] style using [[http://orgmode.org/worg/org-contrib/babel/][Org mode Babel]].

* Code
** Introductory Boilerplate					   :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no :noweb yes
     ;;; init-linum-mode.el --- Configuration for linum-mode
     ;;
     ;;; Commentary:
     ;; This file is tangled from init-linum-mode.org.
     ;; Changes made here will be overwritten by changes to that Org file.

     ;;; Code:
   #+END_SRC

** Specify Dependencies						   :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no
     (require 'use-package)
   #+END_SRC

** Load ~display-line-numbers~
   #+BEGIN_SRC emacs-lisp :tangle yes :noweb no-export
     (use-package display-line-numbers
       ;; Only load this package if the following code evaluates to non-nil.
       :if
       <<display-line-numbers/if>>

       ;; This package is included in Emacs.
       :straight nil

       ;; Load this package after the following packages.
       :after (validate)

       ;; For each element in the following list, hook the value function on the key function(s).
       :hook
       ((prog-mode) . display-line-numbers-mode)

       :config
       <<display-line-numbers/config>>)
   #+END_SRC

*** Conditional Loading (~:if~)
    :PROPERTIES:
    :DESCRIPTION: Define condition for loading ~display-line-numbers~.
    :HEADER-ARGS+: :noweb-ref display-line-numbers/if
    :END:

    ~display-line-numbers~ was added in GNU Emacs 26.1.

    #+BEGIN_SRC emacs-lisp
      (not (version< "26.1" emacs-version))
    #+END_SRC

*** Post-Load Execution (~:config~)
    :PROPERTIES:
    :HEADER-ARGS+: :noweb-ref display-line-numbers/config
    :END:

    Display relative line numbers for all lines except the current line.

    #+BEGIN_SRC emacs-lisp
      (validate-setq display-line-numbers-type 'relative)
    #+END_SRC

    Display the absolute line number of the current line.

    #+BEGIN_SRC emacs-lisp
      (setq display-line-numbers-current-absolute t)
    #+END_SRC

** Ending Boilerplate                                              :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes
     (provide 'init-linum-mode)
     ;;; init-linum-mode.el ends here
   #+END_SRC
