#+TITLE: TeX Configuration
#+AUTHOR: Joseph M LaFreniere (lafrenierejm)
#+EMAIL: joseph@lafreniere.xyz
#+PROPERTY: header-args+ :comments link
#+PROPERTY: header-args+ :tangle no

* License
  All code sections in this file are licensed under [[https://gitlab.com/lafrenierejm/dotfiles/blob/master/LICENSE][an ISC license]] except when otherwise noted.
  All prose in this file is licensed under [[https://creativecommons.org/licenses/by/4.0/][CC BY 4.0]] except when otherwise noted.

* About This File
  This file contains my configuration for working with {La,Lua,Xe}TeX.
  This file is written in the [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]] style using [[http://orgmode.org/worg/org-contrib/babel/][Org-mode Babel]].

* Code
** Introductory Boilerplate
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no
     ;;; init-tex.el --- Configuration for TeX

     ;;; Commentary:
     ;; This file is tangled from init-tex.org.
     ;; Changes made here will be overwritten by changes to that Org file.

     ;;; Code:
   #+END_SRC

** Dependencies
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no
     (require 'use-package)
   #+END_SRC

** Load AUCTeX
   AUCTeX adds advice to Emacs's existing TeX modes.
   As such, AUCTeX cannot be loaded with ~use-package~ directly.
   Instead, we can hook onto ~tex-site~ and specify a custom package with ~:straight~.

   #+BEGIN_SRC emacs-lisp :tangle yes :noweb yes
     (use-package tex
       :straight (auctex :host github :repo "raxod502/auctex"
                         :branch "fork/1"
                         :files (:defaults (:exclude "doc/*.texi")))

       ;; Load the parent package after the following packages have been loaded.
       :after (validate)

       ;; Customize the following variables.
       :custom
       (TeX-auto-save t "Automatically save style information with the buffer.")
       (TeX-parse-self t "Parse files after loading them.")
       (TeX-master nil "Query for the mast file.")
       (TeX-view-program-selection '((output-pdf "PDF Tools")) "Use PDF Tools to view PDF output.")
       (TeX-source-correlate-start-server t "Automatically start the server for correlating allTeX's output back to the source.")
       (TeX-electric-sub-and-superscript t "Automatically add braces after "^" or "_" in a math environment.")
       (Tex-electric-math (cons "$" "$") "Automatically insert a matching "$" to delimit math environments.")
       (reftex-plug-into-AUCTeX t "Use ReFTeX")

       ;; Execute the following code after the parent package has been loaded.
       :config
       <<tex/config>>)
   #+END_SRC

*** Post-Load Execution
    :PROPERTIES:
    :HEADER-ARGS+: :noweb-ref tex/config
    :END:

    Update PDF buffers are successful compilation.

    #+BEGIN_SRC emacs-lisp
      (add-hook 'TeX-after-compilation-finished-functions
		'TeX-revert-document-buffer)
    #+END_SRC

    Apply (plain)TeX-specific settings.

     #+BEGIN_SRC emacs-lisp
       (defun init-tex/config/plain-tex ()
         "Configure `plain-tex-mode'."
         <<tex/config/plain-tex>>)
       (add-hook 'plain-TeX-mode-hook
                 #'init-tex/config/plain-tex)
     #+END_SRC

    Apply LaTeX-specific settings.

    #+BEGIN_SRC emacs-lisp
      (defun init-tex/configure-latex-mode ()
        "Configure `LaTeX-mode'."
        <<tex/config/latex>>)
      (add-hook 'LaTeX-mode-hook
                #'init-tex/configure-latex-mode)
      (add-hook 'LaTeX-mode-hook #'turn-on-reftex)
    #+BEGIN_SRC emacs-lisp :tangle no
      (latex-math-mode)
    #+END_SRC

**** allTeX Configuration
     :PROPERTIES:
     :noweb-ref: tex/config/all-tex
     :END:

     Set "`" to a prefix for typing mathematics symbols.

     #+BEGIN_SRC emacs-lisp
       (LaTeX-math-mode)
     #+END_SRC

     Automatically add braces after "^" or "_" in a math environment.

    #+BEGIN_SRC emacs-lisp
      (set (make-variable-buffer-local 'TeX-electric-sub-and-superscript) t)
    #+END_SRC

     Enable spellchecking.

     #+BEGIN_SRC emacs-lisp
       (setq ispell-parser 'tex)
       (flyspell-mode 1)
     #+END_SRC

**** (plain)TeX Configuration
     :PROPERTIES:
     :noweb-ref: tex/config/plain-tex
     :END:

     Include the allTeX configuration.

     #+BEGIN_SRC emacs-lisp
       <<tex/config/all-tex>>
     #+END_SRC

     Automatically insert a matching "$" to delimit math environments.

     #+BEGIN_SRC emacs-lisp
       (set (make-variable-buffer-local 'TeX-electric-math)
            (cons "$" "$"))
     #+END_SRC

**** LaTeX Configuration
     :PROPERTIES:
     :noweb-ref: tex/config/latex
     :END:

     Include the allTeX configuration.

     #+BEGIN_SRC emacs-lisp
       <<tex/config/all-tex>>
     #+END_SRC

     Automatically convert "$" to LaTeX-style math environment delimeters.

     #+BEGIN_SRC emacs-lisp
       (set (make-variable-buffer-local 'TeX-electric-math)
            (cons "\\(" "\\)"))
     #+END_SRC

     Replace double quotes with =\enquote{}= if the csquotes package is loaded.

     #+BEGIN_SRC emacs-lisp
	(validate-setq LaTeX-csquotes-open-quote "\\enquote{"
		       LaTeX-csquotes-close-quote "}")
     #+END_SRC

** Load AUCTeX Latexmk
   Tomoya Tanjo (tom-tan)'s [[https://github.com/tom-tan/auctex-latexmk][AUCTeX Latexmk]] package adds =latexmk= as a compilation target for AUCTeX.
   [[https://ctan.org/pkg/latexmk][Latexmk]] itself is a Perl script that automates the steps needed to fully compile a TeX document.
   Latexmk is included as part of both MaCTeX and MikTeX.

   #+BEGIN_SRC emacs-lisp :tangle yes :noweb yes
     (use-package auctex-latexmk
       ;; Only load this package if the following condition is met.
       :if (executable-find "latemk")

       ;; Load this package eagerly.
       :demand

       ;; Load this package after the following packages.
       :after (tex)

       ;; Execute the following code after the package has been loaded.
       :config
       <<auctex-latexmk/config>>)
   #+END_SRC

*** Variable Customization (~:custom~)
    :PROPERTIES:
    :HEADER-ARGS+: :noweb-ref auctex-latexmk/custom
    :END:

    Use the =-pdf= flag when ~TeX-PDF-mode~ is active.

    #+BEGIN_SRC emacs-lisp
      (auctex-latexmk-inherit-TeX-PDF-mode t)
    #+END_SRC

    Workaround a MikTeX bug by disabling ~TeX-file-line-error~.

    #+BEGIN_SRC emacs-lisp
      (TeX-file-line-error nil)
    #+END_SRC

    Set =latexmk= as the default compilation method.

    #+BEGIN_SRC emacs-lisp
      (TeX-command-default "LatexMk")
    #+END_SRC

*** Post-Load Execution
    :PROPERTIES:
    :HEADER-ARGS+: :noweb-ref auctex-latexmk/config
    :END:

    Run the package's setup.

    #+BEGIN_SRC emacs-lisp
      (auctex-latexmk-setup)
    #+END_SRC

** Ending Boilerplate
   #+BEGIN_SRC emacs-lisp :tangle yes
     (provide 'init-tex)
     ;;; init-tex.el ends here
   #+END_SRC
