# Symlink this file to ~/.bashrc

# Bash initialization for interactive non-login shells and
# for remote shells (info "(bash) Bash Startup Files").

# Export 'SHELL' to child processes.  Programs such as 'screen'
# honor it and otherwise use /bin/sh.
export SHELL

if [[ $- != *i* ]]; then
    # We are being invoked from a non-interactive shell.  If this
    # is an SSH session (as in "ssh host command"), source
    # /etc/profile so we get PATH and other essential variables.
    [[ -n "$SSH_CLIENT" ]] && source /etc/profile

    # Don't do anything else.
    return
fi

# Source the system-wide file.
if [[ -f /etc/bashrc ]]; then
    source /etc/bashrc
fi

# Read and export the XDG environment variables.
XDG_CONFIG_HOME="$HOME"/etc
if [[ ! -d "$XDG_CONFIG_HOME" ]]; then
   XDG_CONFIG_HOME="$HOME/.config"
fi
if [[ -d "$XDG_CONFIG_HOME" ]]; then
    export XDG_CONFIG_HOME
    shopt -s extglob
    for file in "$XDG_CONFIG_HOME"/sh/[0-9].*.?(ba)sh; do
	. "$file"
    done
fi
