#!/usr/bin/env sh

# Source `/etc/profile` if it exists.
[ -e /etc/profile ] && . /etc/profile

if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Set configuration home.
export XDG_CONFIG_HOME="$HOME"/.config

# Read and export the XDG environment variables.
USER_DIRS="$XDG_CONFIG_HOME/xdg/user-dirs.linux.dirs"
if [ "$(uname)" = 'Darwin' ]; then
    USER_DIRS="$XDG_CONFIG_HOME/xdg/user-dirs.mac.dirs"
fi
if [ -f "$USER_DIRS" ]; then
    while read -r line; do
	line="$(echo "$line" | sed -e "s|\$HOME|$HOME|" -e 's|"||g')"
	export "${line?}"
    done <"$USER_DIRS"
fi

# Set PATH.
GUIX_PROFILE="$XDG_CONFIG_HOME"/guix/current
if [ -f "$GUIX_PROFILE" ]; then
    export GUIX_PROFILE
    PATH="$GUIX_PROFILE/bin:$PATH"
    hash guix
fi
LOCAL_BIN="$HOME/.local/bin"
mkdir -p "$LOCAL_BIN"
export PATH="$LOCAL_BIN:$PATH"

NIX_BINS="$HOME/.nix-profile/bin"
if [ -d "$NIX_BINS" ]; then
    export PATH="$NIX_BINS:$PATH"
fi
