#!/bin/sh

# Stop any running instances.
pkill xcape

# Bind caps lock to escape on tap, left super on hold.
xmodmap -e "remove Lock = Caps_Lock"
xmodmap -e "keysym Caps_Lock = Super_L"
# xmodmap -e "add Lock = Caps_Lock"
xcape -e "Super_L=Escape"

# Bind enter to right super on hold.
xmodmap -e "keycode 36 = Super_R"
xmodmap -e "keycode any = Return" # xcape needs a keycode
xcape -e "Super_R=Return"

# Bind space to control on hold.
xmodmap -e "keycode 65 = Hyper_L" # bind space to an unused modifier keysym
xmodmap -e "remove mod4 = Hyper_L" # unbind the modifier
xmodmap -e "add Control = Hyper_L"
xmodmap -e "keycode any = space" # map space to an unused keycode
xcape -e "Hyper_L=space" # generate the keysym on tap
