#!/bin/sh

user_resources="${HOME}/.config/X11/Xresources"
user_modmap="${HOME}/.config/X11/Xmodmap"
user_xcape="${HOME}/.config/X11/xcape"
sys_resources='/etc/X11/xinit/.Xresources'
sys_modmap='/etc/X11/xinit/.Xmodmap'

# Merge settings from system files
if [ -f "${sys_resources}" ]; then
	xrdb -merge "$sys_resources"
fi
if [ -f "${sys_modmap}" ]; then
	xmodmap "${sys_modmap}"
fi

# Apply user settings
if [ -f "${user_resources}" ]; then
	xrdb "${user_resources}"
fi
if [ -f "${user_modmap}" ]; then
	xmodmap "${user_modmap}"
fi
if [ -f "$user_xcape" ]; then
	. "$user_xcape"
fi


# Daemonize Emacs and start EXWM
emacs --daemon -f exwm-enable
exec emacsclient --create-frame --eval '(eshell-find-eshell-here)'
