# This file is used to set environment variables

# Set the default editor to vim
export EDITOR=vim

# Set the default pager to less
## '-i' is intelligent case-sensitivity
export PAGER='less -i'

# Set the first terminal to be tried by i3
export TERMINAL=st

# Set the base directory to which user-specific configuration files should be written
export XDG_CONFIG_HOME="${HOME}/.config/"

# gpg-agent
export GPG_TTY=${TTY}
