# This is the main user configuration file
# It is sourced when zsh is started as an interactive shell
# ##############################################################################

# Alway run inside tmux
## Attempt to attach if SSH'd in
if [[ -n "$SSH_CLIENT" ]] && [[ -z "$TMUX" ]]; then
	tmux attach || tmux new-session
## Else replace shell with tmux session
elif [[ -z "$TMUX" ]]; then
	exec tmux
fi

# Use vi mode
bindkey -v
## Set a 1ms delay on pressing ESC
export KEYTIMEOUT=1

# Enable autocompletion
autoload -U compinit
compinit

# History settings
if [ -d "${HOME}/.local/share/zsh" ]; then
	HISTFILE="${HOME}/.local/share/history.txt"
else
	mkdir -p "${HOME}/.local/share/zsh"
	HISTFILE="${HOME}/.local/share/history.txt"
fi
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory nomatch
## Ignore duplicate lines in the history
setopt HIST_IGNORE_DUPS
unsetopt autocd beep extendedglob notify

# Source external files
if [ -d "${ZDOTDIR}/interactive" ]; then
	for file in $(find "${ZDOTDIR}/interactive" -name '*.zsh' -print); do
		source "${file}"
	done
elif [ -d "${HOME}/.config/zsh/interactive" ]; then
	for file in $(
			find "${HOME}/.config/zsh/interactive" -name '*.zsh' -print
	); do
		source "${file}"
	done
fi

# Set the left-aligned prompt
## Display the current directory, shortening $HOME to '~'
## Display '#' if root, '%' otherwise
PS1="%~%# "
