# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "sd_mod"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/3c56e946-4b05-44fb-8463-1245b82ea8d5";
      fsType = "btrfs";
      options = ["compress=zstd"];
    };
    "/home" = {
      device = "/dev/disk/by-uuid/3c56e946-4b05-44fb-8463-1245b82ea8d5";
      fsType = "btrfs";
      options = ["compress=zstd" "subvol=home"];
    };
    "/nix" = {
      device = "/dev/disk/by-uuid/3c56e946-4b05-44fb-8463-1245b82ea8d5";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "compress=zstd"
        "noatime" # disregard access times to reduce disk wear
      ];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/3596-EF0F";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/463241cf-e75d-4fbb-998b-950459dc88d2";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = true;
}
