# Bash initialization for interactive non-login shells and
# for remote shells (info "(bash) Bash Startup Files").

# Export 'SHELL' to child processes.  Programs such as 'screen'
# honor it and otherwise use /bin/sh.
export SHELL

export EDITOR="emacsclient --alternate-editor='' --tty %s"
export VISUAL="emacsclient --alternate-editor='' --create-frame %s"

if [[ $- != *i* ]]
then
    # We are being invoked from a non-interactive shell.  If this
    # is an SSH session (as in "ssh host command"), source
    # /etc/profile so we get PATH and other essential variables.
    [[ -n "$SSH_CLIENT" ]] && source /etc/profile

    # Don't do anything else.
    return
fi

# Source the system-wide file.
if [[ -f /etc/bashrc ]]; then
    source /etc/bashrc
fi

# Adjust the prompt depending on whether we're in 'guix environment'.
if [ -n "$GUIX_ENVIRONMENT" ]
then
    PS1='\u@\h \w [env]\$ '
else
    PS1='\u@\h \w\$ '
fi
alias ls='ls -p --color=auto'
alias ll='ls -l'
alias grep='grep --color=auto'

# Read and export the XDG environment variables.
export XDG_CONFIG_HOME="$HOME"/etc
USER_DIRS="$XDG_CONFIG_HOME"/user-dirs.dirs
if [[ -f "$USER_DIRS" ]]; then
    while read line; do
	line="$(sed -e "s|\$HOME|$HOME|" -e 's|"||g' <<<$line)"
	export "$line"
    done <"$USER_DIRS"
fi

# Set PATH.
GUIX_PROFILE="$XDG_CONFIG_HOME"/guix/current
if [[ -f "$GUIX_PROFILE" ]]; then
    export GUIX_PROFILE
    PATH="$GUIX_PROFILE/bin:$PATH"
    hash guix
fi
LOCAL_BIN="$HOME/.local/bin"
mkdir -p "$LOCAL_BIN"
export PATH="$LOCAL_BIN:$PATH"
