#+TITLE: Projectile Configuration
#+AUTHOR: Joseph M LaFreniere (lafrenierejm)
#+EMAIL: joseph@lafreniere.xyz
#+PROPERTY: header-args+ :comments link
#+PROPERTY: header-args+ :tangle no

* License                                                          :noexport:
  All code sections in this file are licensed under [[https://gitlab.com/lafrenierejm/dotfiles/blob/master/LICENSE][an ISC license]] except when otherwise noted.
  All prose in this file is licensed under [[https://creativecommons.org/licenses/by/4.0/][CC BY 4.0]] except when otherwise noted.

* About This File
  This file loads and configures Emacs's built-in projectile package.
  This file is written in a [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]] style using [[http://orgmode.org/worg/org-contrib/babel/][Org mode Babel]].

* Code
** Introductory Boilerplate                                        :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no :export no
     ;;; init-projectile.el --- Configuration for projectile

     ;;; Commentary:
     ;; This file is tangled from init-projectile.org.
     ;; Changes made here will be overwritten by changes to that Org file.

     ;;; Code:
   #+END_SRC

** Specify Dependencies                                            :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes :padline no :export no
     (require 'general)
     (require 'use-package)
   #+END_SRC

** Load Projectile
   #+BEGIN_SRC emacs-lisp :tangle yes :noweb no-export
     (use-package projectile
       ;; Load this package eagerly.
       :demand

       ;; Add the following keybindings.
       :general
       <<projectile/general>>

       ;; Customize the following variables.
       :custom
       <<projectile/custom>>

       :init
       <<projectile/init>>)
   #+END_SRC

*** Auto-Loading Keybindings (~:general~)
    :PROPERTIES:
    :HEADER-ARGS+: :noweb-ref projectile/general
    :END:

    #+BEGIN_SRC emacs-lisp
      (:keymaps 'projectile-mode-map
		"C-c p" 'projectile-command-map)
    #+END_SRC

*** Pre-Load Evaluation (~:init~)
    :PROPERTIES:
    :HEADER-ARGS+: :noweb-ref projectile/init
    :END:

    Enable ~projectile-mode~ globally.

    #+BEGIN_SRC emacs-lisp
      (projectile-mode +1)
    #+END_SRC

*** Variable Customizations (~:custom~)
    :PROPERTIES:
    :HEADER-ARGS+: :noweb-ref projectile/custom
    :END:

    When switching projects, default to opening the ~vc-dir~ at the root of the project.

    #+BEGIN_SRC emacs-lisp
      (projectile-switch-project-action #'projectile-vc)
    #+END_SRC

** Load Counsel Projectile
   #+BEGIN_SRC emacs-lisp :tangle yes :noweb yes
     (use-package counsel-projectile
       :straight
       (counsel-projectile :type git :host github :repo "ericdanan/counsel-projectile")

       ;; Load this package after the following packages.
       :after (counsel projectile)

       ;; Add the following keybindings.
       :general
       (:keymaps 'projectile-mode-map
		 "C-x C-f" #'counsel-projectile-find-file-dwim
		 "C-x C-b" #'counsel-projectile-switch-to-buffer
		 "C-x C-d" #'counsel-projectile-find-dir)

       ;; Customize the following variables.
       :custom
       <<counsel-projectile/custom>>

       ;; Evaluate the following code before loading the package.
       :init
       <<counsel-projectile/init>>)
   #+END_SRC

*** Variable Customization (~:custom~)
    :PROPERTIES:
    :HEADER-ARGS+: :noweb-ref counsel-projectile/custom
    :END:

    When switching projects, default to opening the ~vc-dir~ at the root of the project.

    #+BEGIN_SRC emacs-lisp
      (counsel-projectile-switch-project-action #'counsel-projectile-switch-project-action-vc)
    #+END_SRC

*** Pre-Load Evaluation (~:init~)
    :PROPERTIES:
    :HEADER-ARGS+: :noweb-ref counsel-projectile/init
    :END:

    Enable ~counsel-projectile-mode~.

    #+BEGIN_SRC emacs-lisp
      (counsel-projectile-mode)
    #+END_SRC

** Ending Boilerplate                                              :noexport:
   #+BEGIN_SRC emacs-lisp :tangle yes
     (provide 'init-projectile)
     ;;; init-projectile.el ends here
   #+END_SRC
